# Generated by Django 3.2 on 2024-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bloodbank', models.TextField()),
                ('district', models.TextField()),
                ('number', models.BigIntegerField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('bloodgroup', models.TextField()),
            ],
        ),
    ]
