# Generated by Django 3.2 on 2024-04-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table='doner',
        ),
    ]
